name: Release on tag
on:
    push:
        tags: ["*"]

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Create GitHub Release (auto notes)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  TAG="${GITHUB_REF#refs/tags/}"
                  gh release create "$TAG" --generate-notes
